name: Scheduled Workflow
on:
  schedule:
    - cron: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Build Docker image
        working-directory: ./src
        run: |
          docker build -t my-taxi-app .
        
      - name: Run Docker container
        
        run: |
          docker run -d -p 8000:8000 my-taxi-app
          sleep 5s
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/compute/)
          sleep 100s
          if [[ $response -eq 200 ]]; then
            message="Metrics computed and stored"
            echo $message
          else
            message="Failed to compute metrics"
            echo $message
          fi
          current_date=$(date '+%Y-%m-%d %H:%M:%S')
          touch log.txt
          echo "${current_date}: ${message}" >> log.txt
          git config --global user.email "abusheikabdulrahim2021@gmail.com"
          git config --global user.name "Abusheik008"
          git add .
          git commit -m "Updated metrics at ${current_date}: ${message}"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKENS}}

