name: Scheduled Workflow
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        working-directory: ./src
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django server
        working-directory: ./src
        run: |
          python manage.py runserver
          echo "Django server started at http://127.0.0.1:8000/" 

      - name: Send GET request
        run: |
          sleep 5s
          response=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/compute/)
          if [[ $response -eq 200 ]]; then
            message="Metrics computed and stored"
          else
            message="Failed to compute metrics"
          fi
          current_date=$(date '+%Y-%m-%d %H:%M:%S')
          git config --global user.email "abusheikabdulrahim2021@gmail.com"
          git config --global user.name "Abusheik008"
          git add .
          git commit -m "Update metrics at ${current_date}: ${message}"
          git push
